# Generated by Django 4.1.2 on 2024-06-14 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('foto', models.ImageField(upload_to='fotos_servicios/')),
                ('descripcion', models.TextField()),
            ],
        ),
    ]
